environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

platform:
  - x86

init:
  # As AppVeyor has multiple python install, verify which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version

    # Set the relevant python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: pip --version

  # Check out installed python packages
  - cmd: pip freeze

install:
  - cmd: pip install pyinstaller==3.2

  # Check installed packages again
  - cmd: pip freeze

  - cmd: pyinstaller unzip.spec --onefile

build: None

deploy:
  provider: GitHub
  auth_token:
    secure: 1D2ZAIZ6ZRdrM4U4a6nixsk+r76Uq2/9ev1FkKTbIEjM/2RTXPKdBwPdf2OleIFz
  artifact: /dist\\unzip\.exe/
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only